[server]
port = 8080
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[client]
toolbarMode = "viewer"
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#FCD059"
backgroundColor = "#F5F2EB"
secondaryBackgroundColor = "#FCFBF8"
textColor = "#2B2B2B"